name: Change Title on issue

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run a multi-line script
      run: .\install.ps1 -title "${{ github.event.issue.title }}"
      shell: pwsh
 
